### ISSUE TITLE
Bug: "make docker-build-all" command is failing on main branch

### ISSUE THREAD

**Issue by JingChen23** [vmware-tanzu/cloud-native-security-inspector#162]
```
12:17:43 root@example src ±|main|→ make docker-build-all
go mod tidy
go: creating new go.mod: module tmp
Downloading sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.1
/root/backup/cloud-native-security-inspector/src/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=cnsi-manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/root/backup/cloud-native-security-inspector/src/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
mkdir -p /root/backup/cloud-native-security-inspector/src/testbin
test -f /root/backup/cloud-native-security-inspector/src/testbin/setup-envtest.sh || curl -sSLo /root/backup/cloud-native-security-inspector/src/testbin/setup-envtest.sh https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/v0.8.3/hack/setup-envtest.sh
source /root/backup/cloud-native-security-inspector/src/testbin/setup-envtest.sh; fetch_envtest_tools /root/backup/cloud-native-security-inspector/src/testbin; setup_envtest_env /root/backup/cloud-native-security-inspector/src/testbin; go test ./... -coverprofile cover.out
fetching envtest tools@1.19.2 (into '/root/backup/cloud-native-security-inspector/src/testbin')
kubebuilder/bin/
kubebuilder/bin/etcd
kubebuilder/bin/kubectl
kubebuilder/bin/kube-apiserver
setting up env vars
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/api/v1alpha1	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/cmd/inspector	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/cmd/kubebench	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/cmd/riskmanager	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/controllers	[no test files]
ok  	github.com/vmware-tanzu/cloud-native-security-inspector/src/lib/log	0.014s	coverage: 64.3% of statements
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/data	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/data/cache	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/data/cache/redis	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/data/consumers	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/data/consumers/es	[no test files]
ok  	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/data/consumers/opensearch	0.054s	coverage: 15.1% of statements
ok  	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/data/core	0.010s	coverage: 77.6% of statements
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/data/providers	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/data/providers/harbor	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/data/types	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/data/types/vuln	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/errs	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/inspection	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/inspection/config	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/inspection/data	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/inspection/kubebench	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/inspection/riskmanager	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/policy	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/policy/enforcement	[no test files]
ok  	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/policy/network	0.049s	coverage: 47.9% of statements
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/rest/client	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/rest/client/assessment	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/rest/client/operations	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/rest/models	[no test files]
ok  	github.com/vmware-tanzu/cloud-native-security-inspector/src/pkg/runtime/grpool	0.014s	coverage: 87.3% of statements
F0214 00:18:56.138865   16495 env.go:360] Setup failure: kind not available even after installation
FAIL	github.com/vmware-tanzu/cloud-native-security-inspector/src/test/e2e	0.631s
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/test/e2e/inspectionpolicy	[no test files]
?   	github.com/vmware-tanzu/cloud-native-security-inspector/src/test/e2e/setting	[no test files]
FAIL
make: *** [test] Error 1
```

Should be a regression caused by the e2e test.

**Comment by 4everming** [comment]
The user should have a KIND environment to run E2E tests, otherwise, it will fail. We should mention this in the DevelopGuide.

**Comment by 4everming** [comment]
#13 103.2 > nx@14.8.6 postinstall /protal/node_modules/nx
#13 103.2 > node ./bin/compute-project-graph
#13 103.2
#13 103.4
#13 103.4 > cypress@12.5.1 postinstall /protal/node_modules/cypress
#13 103.4 > node index.js --exec install
#13 103.4
#13 103.8 Installing Cypress (version: 12.5.1)
#13 103.8
#13 103.8 [STARTED] Task without title.
#13 106.8 [FAILED] The Cypress App could not be downloaded.
#13 106.8 [FAILED]
#13 106.8 [FAILED] Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
#13 106.8 [FAILED]
#13 106.8 [FAILED] Otherwise, please check network connectivity and try again:
#13 106.8 [FAILED]
#13 106.8 [FAILED] ----------
#13 106.8 [FAILED]
#13 106.8 [FAILED] URL: https://download.cypress.io/desktop/12.5.1?platform=linux&arch=x64
#13 106.8 [FAILED] Error
#13 106.8 [FAILED]
#13 106.8 [FAILED] ----------
#13 106.8 [FAILED]
#13 106.8 [FAILED] Platform: linux-x64 (Debian - 9.13)
#13 106.8 [FAILED] Cypress Version: 12.5.1
#13 106.8 The Cypress App could not be downloaded.
#13 106.8
#13 106.8 Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
#13 106.8
#13 106.8 Otherwise, please check network connectivity and try again:
#13 106.8
#13 106.8 ----------
#13 106.8
#13 106.8 URL: https://download.cypress.io/desktop/12.5.1?platform=linux&arch=x64
#13 106.8 Error
#13 106.8
#13 106.8 ----------
#13 106.8
#13 106.8 Platform: linux-x64 (Debian - 9.13)
#13 106.8 Cypress Version: 12.5.1
#13 108.0 npm WARN notsup Unsupported engine for @typescript-eslint/parser@5.29.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.5","npm":"6.14.11"})
#13 108.0 npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/parser@5.29.0
#13 108.0 npm WARN notsup Unsupported engine for @typescript-eslint/eslint-plugin@5.29.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.5","npm":"6.14.11"})
#13 108.0 npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/eslint-plugin@5.29.0
#13 108.0 npm WARN notsup Unsupported engine for eslint@8.34.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.5","npm":"6.14.11"})
#13 108.0 npm WARN notsup Not compatible with your version of node/npm: eslint@8.34.0
#13 108.0 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @esbuild/linux-loong64@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/@esbuild/linux-loong64):
#13 108.0 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @esbuild/linux-loong64@0.15.5: wanted {"os":"linux","arch":"loong64"} (current: {"os":"linux","arch":"x64"})
#13 108.0 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-arm64@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-darwin-arm64):
#13 108.0 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-arm64@0.15.5: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
#13 108.0 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-64@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-android-64):
#13 108.0 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-64@0.15.5: wanted {"os":"android","arch":"x64"} (current: {"os":"linux","arch":"x64"})
#13 108.0 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-64@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-freebsd-64):
#13 108.0 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-64@0.15.5: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
#13 108.0 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-arm64@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-freebsd-arm64):
#13 108.0 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-arm64@0.15.5: wanted {"os":"freebsd","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
#13 108.0 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-64@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-darwin-64):
#13 108.0 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-64@0.15.5: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
#13 108.0 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-linux-arm):
#13 108.0 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm@0.15.5: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
#13 108.0 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-arm64@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-android-arm64):
#13 108.0 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-arm64@0.15.5: wanted {"os":"android","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
#13 108.0 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-32@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-linux-32):
#13 108.0 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-32@0.15.5: wanted {"os":"linux","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
#13 108.0 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm64@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-linux-arm64):
#13 108.0 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm64@0.15.5: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
#13 108.0 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-mips64le@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-linux-mips64le):
#13 108.0 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-mips64le@0.15.5: wanted {"os":"linux","arch":"mips64el"} (current: {"os":"linux","arch":"x64"})
#13 108.0 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-ppc64le@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-linux-ppc64le):
#13 108.0 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-ppc64le@0.15.5: wanted {"os":"linux","arch":"ppc64"} (current: {"os":"linux","arch":"x64"})
#13 108.0 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-riscv64@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-linux-riscv64):
#13 108.0 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-riscv64@0.15.5: wanted {"os":"linux","arch":"riscv64"} (current: {"os":"linux","arch":"x64"})
#13 108.0 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-s390x@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-linux-s390x):
#13 108.0 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-s390x@0.15.5: wanted {"os":"linux","arch":"s390x"} (current: {"os":"linux","arch":"x64"})
#13 108.0 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-netbsd-64@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-netbsd-64):
#13 108.0 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-netbsd-64@0.15.5: wanted {"os":"netbsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
#13 108.0 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-sunos-64@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-sunos-64):
#13 108.0 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-sunos-64@0.15.5: wanted {"os":"sunos","arch":"x64"} (current: {"os":"linux","arch":"x64"})
#13 108.0 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-32@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-windows-32):
#13 108.0 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-32@0.15.5: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
#13 108.1 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-64@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-windows-64):
#13 108.1 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-64@0.15.5: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
#13 108.1 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-openbsd-64@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-openbsd-64):
#13 108.1 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-openbsd-64@0.15.5: wanted {"os":"openbsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
#13 108.1 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-windows-arm64@0.15.5 (node_modules/@angular-devkit/build-angular/node_modules/esbuild/node_modules/esbuild-windows-arm64):
#13 108.1 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-windows-arm64@0.15.5: wanted {"os":"win32","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
#13 108.1 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
#13 108.1 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
#13 108.1 npm WARN notsup Unsupported engine for @typescript-eslint/utils@5.29.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.5","npm":"6.14.11"})
#13 108.1 npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/utils@5.29.0
#13 108.1 npm WARN notsup Unsupported engine for @typescript-eslint/typescript-estree@5.29.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.5","npm":"6.14.11"})
#13 108.1 npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/typescript-estree@5.29.0
#13 108.1 npm WARN notsup Unsupported engine for @typescript-eslint/scope-manager@5.29.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.5","npm":"6.14.11"})
#13 108.1 npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/scope-manager@5.29.0
#13 108.1 npm WARN notsup Unsupported engine for @typescript-eslint/types@5.29.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.5","npm":"6.14.11"})
#13 108.1 npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/types@5.29.0
#13 108.1 npm WARN notsup Unsupported engine for @typescript-eslint/visitor-keys@5.29.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.5","npm":"6.14.11"})
#13 108.1 npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/visitor-keys@5.29.0
#13 108.1 npm WARN notsup Unsupported engine for eslint-visitor-keys@3.3.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.5","npm":"6.14.11"})
#13 108.1 npm WARN notsup Not compatible with your version of node/npm: eslint-visitor-keys@3.3.0
#13 108.1 npm WARN notsup Unsupported engine for @typescript-eslint/type-utils@5.29.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.5","npm":"6.14.11"})
#13 108.1 npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/type-utils@5.29.0
#13 108.1 npm WARN notsup Unsupported engine for @eslint/eslintrc@1.4.1: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.5","npm":"6.14.11"})
#13 108.1 npm WARN notsup Not compatible with your version of node/npm: @eslint/eslintrc@1.4.1
#13 108.1 npm WARN notsup Unsupported engine for eslint-scope@7.1.1: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.5","npm":"6.14.11"})
#13 108.1 npm WARN notsup Not compatible with your version of node/npm: eslint-scope@7.1.1
#13 108.1 npm WARN notsup Unsupported engine for espree@9.4.1: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.5","npm":"6.14.11"})
#13 108.1 npm WARN notsup Not compatible with your version of node/npm: espree@9.4.1
#13 108.1 npm WARN @clr/icons@13.0.2 requires a peer of @webcomponents/custom-elements@^1.0.0 but none is installed. You must install peer dependencies yourself.
#13 108.1 npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
#13 108.1
#13 108.1 npm ERR! code ELIFECYCLE
#13 108.1 npm ERR! errno 1
#13 108.1 npm ERR! cypress@12.5.1 postinstall: `node index.js --exec install`
#13 108.1 npm ERR! Exit status 1
#13 108.1 npm ERR!
#13 108.1 npm ERR! Failed at the cypress@12.5.1 postinstall script.
#13 108.1 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#13 108.2
#13 108.2 npm ERR! A complete log of this run can be found in:
#13 108.2 npm ERR!     /root/.npm/_logs/2023-02-14T07_17_53_573Z-debug.log
------
executor failed running [/bin/sh -c npm --unsafe-perm install]: exit code: 1
make: *** [docker-build-portal] Error 1

**Comment by JingChen23** [comment]
This issue is originally track this ask: "why docker-build-all has dependency on KIND ?"

Now this issue has been resolved. But we have inferred 2 more issues:
1. Why on laptop, when we have installed a KIND cluster, we will see the Cypress error when we run e2e test?
2. We need a document to inform the developers the basic steps for running the e2e test during development.

Will create 2 issues to track above.
